---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ if or (eq .KUBE_NAMESPACE .UAT_ENV) (eq .KUBE_NAMESPACE .PROD_ENV) }}webmessenger-pvc{{ else if eq .KUBE_NAMESPACE .BRANCH_ENV }}webmessenger-pvc-{{ .DRONE_SOURCE_BRANCH }}{{ end }}
  namespace: {{ .KUBE_NAMESPACE }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2-encrypted-eu-west-2b
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ if or (eq .KUBE_NAMESPACE .UAT_ENV) (eq .KUBE_NAMESPACE .PROD_ENV) }}webmessenger-logs-pvc{{ else if eq .KUBE_NAMESPACE .BRANCH_ENV }}webmessenger-logs-pvc-{{ .DRONE_SOURCE_BRANCH }}{{ end }}
  namespace: {{ .KUBE_NAMESPACE }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2-encrypted-eu-west-2b
